"""add_unstructured_and_ai_fields

Revision ID: 05f7614940a8
Revises: 9fbdd669ed1b
Create Date: 2026-02-12 22:21:00.654411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05f7614940a8'
down_revision: Union[str, Sequence[str], None] = '9fbdd669ed1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_summary_prompts', sa.Column('response_source', sa.Text(), nullable=True))
    op.add_column('ai_summary_prompts', sa.Column('response_format', sa.Text(), nullable=True))
    op.add_column('ai_summary_prompts', sa.Column('api_model_used', sa.Text(), nullable=True))
    op.add_column('ai_summary_prompts', sa.Column('api_tokens_used', sa.BigInteger(), nullable=True))
    op.add_column('uploaded_files', sa.Column('file_category', sa.Text(), server_default='structured', nullable=False))
    op.add_column('uploaded_files', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('uploaded_files', sa.Column('extraction_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_files', 'extraction_entities')
    op.drop_column('uploaded_files', 'extracted_text')
    op.drop_column('uploaded_files', 'file_category')
    op.drop_column('ai_summary_prompts', 'api_tokens_used')
    op.drop_column('ai_summary_prompts', 'api_model_used')
    op.drop_column('ai_summary_prompts', 'response_format')
    op.drop_column('ai_summary_prompts', 'response_source')
    # ### end Alembic commands ###
